
---
spring:
  profiles.active: dev


# Mybatis-Plus



---
spring:
  profiles: dev
#zookeeper参数
zookeeper:
  servers: 39.107.107.120:2181,39.106.57.233:2181,47.93.29.255:2181
  sessionTimeOut: 6000
  rootNode: /weather
  projectNode: /weather/storage
  productNodes: /weather/products
  masterNode: /weather/storage/master
  onlineNodes: /weather/storage/online

# 消费者配置
kafka:
  consumer:
    servers: 39.107.107.120:9092,39.106.57.233:9092,47.93.29.255:9092
    enableAutoCommit: true
    sessionTimeout: 6000
    autoCommitInterval: 100
    autoOffsetReset: earliest
    pollTimeOut: 100000
  producer:
    servers: 39.107.107.120:9092,39.106.57.233:9092,47.93.29.255:9092
    acks: all
    lingerMs: 10
    bufferMemory: 33554432
    batchSize: 4000
    retries: 3



---
spring:
  profiles: qa


---
spring:
  profiles: uat



---
spring:
  profiles: prod
