
---
spring:
  profiles.active: dev


# Mybatis-Plus



---
spring:
  profiles: dev
#zookeeper参数
zookeeper:
  servers: hadoop001:2181,hadoop002:2181,hadoop003:2181
  sessionTimeOut: 6000
  rootNode: /weather
  projectNode: /weather/storage
  productNodes: /weather/products
  masterNode: /weather/storage/master
  onlineNodes: /weather/storage/online

# 消费者配置
kafka:
  consumer:
    servers: hadoop001:9092,hadoop002:9092,hadoop003:9092
    enableAutoCommit: true
    sessionTimeout: 6000
    autoCommitInterval: 100
    # 设置earliest，配合消费者组id可以从头消费
    autoOffsetReset: earliest
    pollTimeOut: 100000
  producer:
    servers: hadoop001:9092,hadoop002:9092,hadoop003:9092
    # ack设置为all 等价于-1 只有ISR中的所有副本数据全部落地后，才会返回确认报文
    acks: all
    #当lingerMs时间内还未到达batchSize数量时，就会发送数据
    lingerMs: 10
    batchSize: 4000
    bufferMemory: 33554432
    retries: 3



---
spring:
  profiles: qa


---
spring:
  profiles: uat



---
spring:
  profiles: prod
